server:
  port: 8089

spring:
  servlet:
    multipart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 10

# 阿里云百炼
aliyun:
  bailian:
    # deepseek
    ds:
      model: deepSeek-r1
      api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
      api-key: 阿里云百炼API-KEY
    # 千问
    qwen25:
      model: qwen2.5-vl-72b-instruct
      api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
      api-key: 阿里云百炼API-KEY

# 字节火山
bytedance:
  volcengine:
    model: ep-20250213171939-g6vxd
    api-url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
    api-key: 字节火山API-KEY

# 硅基流动
siliconflow:
  model: Pro/deepseek-ai/DeepSeek-R1
  api-url: https://api.siliconflow.cn/v1/chat/completions
  api-key: 硅基流动API-KEY

# Azure
